import { IMarketDepth, InitialMarketDepth } from "./IMarketDepth";

export interface IMarketWatchTokenInfo {
  mwId: number;
  mwName: string;
  scrips: string;
  marketDepth: IMarketDepth;
  showDepth: boolean;
  showMore: boolean;
  stat: String;
  admnDt: String;
  asstCd: String;
  brdLtQty: number;
  buyVarMrgn: String;
  clsEnd: String;
  clsStrt: String;
  cmpName: String;
  combSym: String;
  crdtRtg: String;
  crpActn: String;
  defMkt: String;
  delEdDt: String;
  delStDt: String;
  delUnits: String;
  desc: String;
  dscQty: String;
  exEndDt: String;
  exStrDt: String;
  exch: String;
  exSeg: String;
  expDt: number;
  exprMrgn: number;
  exprDt: String;
  expsnDt: String;
  freeze: number;
  genDen: number;
  genNum: number;
  hPrcRng: number;
  idxId: number;
  instInf: String;
  inst: String;
  instTyp: String;
  isin: String;
  issCptl: String;
  issDt: String;
  issRt: number;
  lPrcRng: number;
  listDt: String;
  lotSz: number;
  ltDt: String;
  matrDt: String;
  maxOrdSz: number;
  maxQty: String;
  mfAmt: String;
  minQty: String;
  minRdQt: number;
  mktPro: String;
  modfr: number;
  multplr: number;
  nav: String;
  navDt: String;
  noMkPro: String;
  optType: String;
  pmtdToTrade: number;
  prcDen: number;
  prcNum: number;
  prcQuot: number;
  prcUnits: String;
  precFrt: String;
  prcn: number;
  recDt: String;
  refKey: String;
  rmk: String;
  seg: String;
  sellVarM: String;
  series: String;
  sipSec: String;
  sptPrc: String;
  strkPrc: number;
  sym: String;
  tenEdDt: String;
  tenStDt: String;
  thrtPrc: String;
  tckSz: number;
  tok: String;
  trdSym: String;
  unqKey: String;
  updTime: String;
  warn: number;
  exchTokens: String;
}

export const InitialTokenInfo = {
  mwId: 0,
  mwName: "",
  scrips: "",

  marketDepth: InitialMarketDepth,

  showDepth: false,

  showMore: false,
  stat: "",
  admnDt: "",
  asstCd: "",
  brdLtQty: 0,
  buyVarMrgn: "",
  clsEnd: "",
  clsStrt: "",
  cmpName: "",
  combSym: "",
  crdtRtg: "",
  crpActn: "",
  defMkt: "",
  delEdDt: "",
  delStDt: "",
  delUnits: "",
  desc: "",
  dscQty: "",
  exEndDt: "",
  exStrDt: "",
  exch: "",
  exSeg: "",
  expDt: 0,
  exprMrgn: 0,
  exprDt: "",
  expsnDt: "",
  freeze: 0,
  genDen: 0,
  genNum: 0,
  hPrcRng: 0,
  idxId: 0,
  instInf: "",
  inst: "",
  instTyp: "",
  isin: "",
  issCptl: "",
  issDt: "",
  issRt: 0,
  lPrcRng: 0,
  listDt: "",
  lotSz: 0,
  ltDt: "",
  matrDt: "",
  maxOrdSz: 0,
  maxQty: "",
  mfAmt: "",
  minQty: "",
  minRdQt: 0,
  mktPro: "",
  modfr: 0,
  multplr: 0,
  nav: "",
  navDt: "",
  noMkPro: "",
  optType: "",
  pmtdToTrade: 0,
  prcDen: 0,
  prcNum: 0,
  prcQuot: 0,
  prcUnits: "",
  precFrt: "",
  prcn: 0,
  recDt: "",
  refKey: "",
  rmk: "",
  seg: "",
  sellVarM: "",
  series: "",
  sipSec: "",
  sptPrc: "",
  strkPrc: 0,
  sym: "",
  tenEdDt: "",
  tenStDt: "",
  thrtPrc: "",
  tckSz: 0,
  tok: "",
  trdSym: "",
  unqKey: "",
  updTime: "",
  warn: 0,
  exchTokens: "",
};
