/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed0e6185-d360-46b4-848c-ad67fa2a460e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yUvgmA5a3",
    "aws_user_pools_web_client_id": "1tmg5j17m1t08m6eeofqivrmnd",
    "oauth": {}
};


export default awsmobile;
